name: RPN Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Create environment files
        run: |
          # Root .env
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" > .env
          
          # Core .env
          mkdir -p core
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" > core/.env
          
          # Backend .env
          mkdir -p backend
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" > backend/.env
          echo "CORE_MODULE_PATH=../core" >> backend/.env
          echo "ALLOW_ORIGINS=http://localhost:3000" >> backend/.env
          
          # Frontend .env
          mkdir -p frontend
          echo "NEXT_PUBLIC_API_URL=http://localhost:8000" > frontend/.env
      
      - name: Install core dependencies
        run: |
          cd core
          pip install -e .
          pip install pytest psycopg2-binary
          
      - name: Debug environment
        run: |
          cd core
          echo "DATABASE_URL from environment: $DATABASE_URL"
          echo "Content of .env file:"
          cat .env
          echo "Installed packages:"
          pip list
          echo "Files in db directory:"
          ls -la db/
      
      - name: Run core tests
        run: |
          cd core
          # Run tests with SQLite only first
          python -m pytest tests/test_db.py -v
          # Then run all tests
          python -m pytest
      
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest fastapi
      
      - name: Setup backend tests
        run: |
          cd backend
          # Create tests directory if it doesn't exist
          mkdir -p tests
          
          # Create a basic test file to ensure pytest finds tests
          cat > tests/test_basic.py << 'EOF'
          def test_hello():
              """A simple test to verify pytest is working."""
              assert True
              
          def test_import():
              """Test that we can import main app modules."""
              try:
                  import main
                  assert True
              except ImportError:
                  assert False, "Failed to import main module"
          EOF
      
      - name: Run backend tests
        run: |
          cd backend
          python -m pytest -v
          # Run the API tests explicitly
          python -m pytest tests/test_api.py -v
      
      - name: Run backend tests in Docker
        run: |
          # Build the test stage Docker image
          docker build -t rpn-calculator-backend:test --target test -f backend/Dockerfile .
          # Run the tests in Docker
          docker run --rm rpn-calculator-backend:test
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

  approve-merge:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Tests passed, ready to merge
        run: echo "All tests have passed. This PR can be merged when ready." 